-- ============================================================
-- CineSuper
-- Phase 2 - Database Tables
-- ============================================================

DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS genres;


-- ============================================================
-- 1. GENRES
-- ============================================================

CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);


-- ============================================================
-- 2. MOVIES
-- ============================================================

CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    release_year INT NOT NULL,
    language TEXT NOT NULL,
    duration_min INT NOT NULL,
    description TEXT,
    poster_url TEXT,
    genre_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT movies_release_year_check
        CHECK (release_year BETWEEN 1900 AND 2100),

    CONSTRAINT movies_duration_check
        CHECK (duration_min > 0),

    CONSTRAINT movies_genre_fk
        FOREIGN KEY (genre_id)
        REFERENCES genres(id)
);


-- ============================================================
-- 3. REVIEWS
-- ============================================================

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL,
    reviewer_name TEXT NOT NULL,
    rating INT NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT reviews_rating_check
        CHECK (rating BETWEEN 1 AND 5),

    CONSTRAINT reviews_movie_fk
        FOREIGN KEY (movie_id)
        REFERENCES movies(id)
);